# Generated by Django 2.1.7 on 2021-04-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0005_auto_20200712_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='default.jpeg', upload_to='genres')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='', null=True, upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='musicapp.Genre'),
        ),
    ]
