# Generated by Django 2.1.7 on 2021-04-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_auto_20210412_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.AddField(
            model_name='song',
            name='SongType',
            field=models.CharField(choices=[('R&B/Soul', 'R&B/Soul'), ('Rock', 'Rock'), ('Jazz/Blues', 'Jazz/Blues'), ('Emo', 'Emo'), ('Bomb bap', 'Bomb bap'), ('Trap', 'Trap'), ('Auto-tunes', 'Auto-tunes'), ('Canton-pop', 'Canton-pop')], default='', max_length=20),
        ),
    ]
