# Generated by Django 2.1.7 on 2021-04-17 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0007_auto_20210414_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='song',
            name='type',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='SongType',
            field=models.CharField(choices=[('R&B/Soul', 'R&B/Soul'), ('Rock', 'Rock'), ('Jazz/Blues', 'Jazz/Blues'), ('Emo', 'Emo'), ('Bomb bap', 'Bomb bap'), ('Trap', 'Trap'), ('Auto-tunes', 'Auto-tunes')], default='', max_length=20),
        ),
    ]
