# Generated by Django 2.1.7 on 2021-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_auto_20210417_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='Creator',
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='song_file'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.FileField(upload_to='song_cover'),
        ),
    ]
