# Generated by Django 2.1.7 on 2021-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_auto_20210428_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
