# Generated by Django 2.0.2 on 2021-01-14 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import index.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_album_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='default.jpeg', upload_to='genres')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='is_favorite',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_title',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='playtime',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='song',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(default='', upload_to=index.models.song_directory_path),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Song name'),
        ),
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='favorite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Song'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='index.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='index.Genre'),
        ),
    ]
